### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by ghost** [softawaregmbh/library-authentication#1]
The code is great and clean. I'm developing something along those lines. Can you help me with a question? How can I test this code in order to pass AppId and AppKey through Postman 6.4.1? Thank you very much.

**Comment by ghost** [comment]
I got it... many thanks.


function S4() {
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
}

function GetNonce() {
    return (S4() + S4() + S4()+ S4() + S4() + S4() + S4()+ S4()).toLowerCase();
}

function GetTimeStamp() {
    var d = new Date();
    return Math.round(d.getTime() / 1000);
}

function getAuthHeader(httpMethod, requestUrl, requestBody) {
    var AUTH_TYPE = 'Hmac';
    var APP_ID = '<my_app_id>';
    var API_KEY = '<my_api_key>';
    
    var requestContentBase64String = '';
    
    requestUrl = requestUrl.replace(/{{(\w*)}}/g,function(str,key) {return environment[key]});
    requestUrl = requestUrl.toLowerCase();
    var requestUri = encodeURIComponent(requestUrl);
    
    var requestHttpMethod = httpMethod;
    
    var requestTimeStamp = GetTimeStamp()
    
    var nonce = GetNonce();

    var bodyHash="";
    
    if (httpMethod == 'GET' || !requestBody) {
        requestBody = ''; 
    } else {
        var requestContentHash = CryptoJS.MD5(requestBody);
        requestContentBase64String = CryptoJS.enc.Base64.stringify(requestContentHash);
    }  
    
    var signatureRawData = APP_ID + httpMethod + requestUri + requestTimeStamp + nonce + requestContentBase64String;
    
    var apiKeyBytes = CryptoJS.enc.Base64.parse(API_KEY);
    
    var signatureBytes = CryptoJS.HmacSHA256(signatureRawData, apiKeyBytes);
    var requestSignatureBase64String = CryptoJS.enc.Base64.stringify(signatureBytes);

    var authHeader = AUTH_TYPE + " " + APP_ID + ':' + requestSignatureBase64String + ':' + nonce + ':' + requestTimeStamp;

    return authHeader;
}

postman.setEnvironmentVariable('hmacAuthHeader', getAuthHeader(request.method, request.url, request.data));

**Comment by cxbrgr** [comment]
Thanks for the ground work @ghost!

As my request body had some postman variables that are randomized each request I needed to modify the script slightly.

For anyone interested just add it as a **Pre-request Script** and set up the two environement variables:

- AppId
- AppKey

Alternativly you can simply replace `pm.environment.get("AppId");` and `pm.environment.get("AppKey");`  in the script and put your id and key directly there.

This version of the script should handle variables in the requesturl as well as in the requestbody.

```
function GetSecondsSinceEpoch() {
    return Math.floor(Date.now() / 1000)
}

function GetNonce() {
    let guid = pm.variables.replaceIn('{{$guid}}')
    return guid.replace(/-/g, '').toLowerCase()
}

function getAuthHeader() {
    var AUTH_TYPE = 'Hmac';
    var APP_ID = pm.environment.get("AppId");
    var API_KEY = pm.environment.get("ApiKey");

    var requestUrl = pm.variables.replaceIn(pm.request.url).toString().toLowerCase();
    var requestUri = encodeURIComponent(requestUrl);
    var requestMethod = request.method

    var requestTimeStamp = GetSecondsSinceEpoch()
    var nonce = GetNonce();

    var rawBody = pm.request.body.raw;
    var requestContentBase64String = '';

    if (requestMethod == 'GET' || !rawBody) {
        requestBody = '';
    } else {
        // get request body with resolved variables
        var requestBody = pm.variables.replaceIn(rawBody);
        // update the request body to have identical random variables
        pm.request.body.update(requestBody);
        var requestContentHash = CryptoJS.MD5(requestBody);
        requestContentBase64String = CryptoJS.enc.Base64.stringify(requestContentHash);
    }

    var signatureRawData = APP_ID + requestMethod + requestUri + requestTimeStamp + nonce + requestContentBase64String;
    var apiKeyBytes = CryptoJS.enc.Base64.parse(API_KEY);

    var signatureBytes = CryptoJS.HmacSHA256(signatureRawData, apiKeyBytes);
    var requestSignatureBase64String = CryptoJS.enc.Base64.stringify(signatureBytes);

    return AUTH_TYPE + " " + APP_ID + ':' + requestSignatureBase64String + ':' + nonce + ':' + requestTimeStamp;
}

var authHeader = getAuthHeader();
pm.request.headers.add({
  key: "Authorization",
  value: authHeader
});
```
