### ISSUE TITLE
Adding to HmacAuthenticatedApps at runtime

### ISSUE THREAD

**Issue by johnhamm** [softawaregmbh/library-authentication#6]
I'd like to have apps register at runtime through another channel and update the HmacAuthenticatedApps dictionary accordingly.  I can't think of a way to do this, aside from perhaps making a static dictionary in the Startup class and passing that to the AddHmacAuthentication configureOptions action.  However, this is probably not thread-safe.  What is the recommended way to handle this use case?

**Comment by meinsiedler** [comment]
Hi John,
thanks for reaching out.

We currently don't support adding or removing apps on runtime, but this is a great feature, so we'll implement it and provide a new version.

**Comment by meinsiedler** [comment]
Hi,
please check out our [new Version 3.2 on NuGet](https://www.nuget.org/packages/softaware.Authentication.Hmac.AspNetCore/3.2.0).

You can now implement and register your own `IHmacAuthorizationProvider` where you can resolve your HMAC apps however you want. Take a look at our [updated README](https://github.com/softawaregmbh/library-authentication#softawareauthenticationhmacaspnetcore) for details.

**Comment by johnhamm** [comment]
Wow that was fast!  That's perfect.
